Section "Monitor"
    Identifier "HDMI-1"
    Option "Primary" "true"
EndSection

Section "Device"
    Identifier "HDMI-GPU"
    Driver "modesetting"
    Option "Monitor-HDMI-1" "HDMI-1"
EndSection

Section "Screen"
    Identifier "ScreenHDMI"
    Device "HDMI-GPU"
    Monitor "HDMI-1"
EndSection

Section "ServerLayout"
    Identifier "LayoutHDMI"
    Screen "ScreenHDMI"
EndSection

