Section "Monitor"
    Identifier "DSI-1"
EndSection

Section "Device"
    Identifier "DSI-GPU"
    Driver "modesetting"
    Option "Monitor-DSI-1" "DSI-1"
EndSection

Section "Screen"
    Identifier "ScreenDSI"
    Device "DSI-GPU"
    Monitor "DSI-1"
EndSection

Section "ServerLayout"
    Identifier "LayoutDSI"
    Screen "ScreenDSI"
EndSection
